/* Auto-generated by generate-uns-measurements.ts. Do not edit by hand. */
export const GeneratedPhysicalMeasurements = {
  /**
   * Amper
   */
  "ampere": "A",
  /**
   * Bajti
   */
  "b": "B",
  /**
   * Bar
   */
  "bar": "bar",
  /**
   * Bit
   */
  "bit": "bit",
  /**
   * Bajt
   */
  "byte": "byte",
  /**
   * Stopinje Celzija
   */
  "celsius": "°C",
  /**
   * Centimeter na sekundo
   */
  "centimeterpersecond": "cm/s",
  /**
   * Kubični meter
   */
  "cubicmeter": "m^3",
  /**
   * Kubični meter na uro
   */
  "cubicmeterperhour": "m^3/h",
  /**
   * Kubični meter na sekundo
   */
  "cubicmeterpersecond": "m^3/s",
  /**
   * Dan
   */
  "day": "day",
  /**
   * Decibel
   */
  "decibel": "dB",
  /**
   * Stopinja
   */
  "degree": "°",
  /**
   * Stopinje Fahrenheita
   */
  "fahrenheit": "°F",
  /**
   * Čevlji
   */
  "feet": "ft",
  /**
   * Galona
   */
  "gallon": "gal",
  /**
   * Gigadžul
   */
  "gigajoule": "GJ",
  /**
   * Gram
   */
  "gram": "g",
  /**
   * Herc
   */
  "hertz": "Hz",
  /**
   * Ura
   */
  "hour": "h",
  /**
   * Džul
   */
  "joule": "J",
  /**
   * Kelvin
   */
  "kelvin": "K",
  /**
   * Kiloamper
   */
  "kiloampere": "kA",
  /**
   * Kilogram
   */
  "kilogram": "kg",
  /**
   * Kilodžul
   */
  "kilojoule": "kJ",
  /**
   * Kilometer
   */
  "kilometer": "km",
  /**
   * Kilometer na uro
   */
  "kilometerperhour": "km/h",
  /**
   * Kilovolt
   */
  "kilovolt": "kV",
  /**
   * Kilovolt-amper
   */
  "kilovoltampere": "kVA",
  /**
   * Kilovolt-reaktivni amper
   */
  "kilovoltamperereactive": "kVAR",
  /**
   * Kilowatt
   */
  "kilowatt": "kW",
  /**
   * Kilowattna ura
   */
  "kilowatthour": "kWh",
  /**
   * Liter
   */
  "liter": "l",
  /**
   * Megaamper
   */
  "megaampere": "MA",
  /**
   * Megagram na uro
   */
  "megagramperhour": "Mg/h",
  /**
   * Megadžul
   */
  "megajoule": "MJ",
  /**
   * Megavolt
   */
  "megavolt": "MV",
  /**
   * Megavolt-amper
   */
  "megavoltampere": "MVA",
  /**
   * Megavolt-reaktivni amper
   */
  "megavoltamperereactive": "MVAR",
  /**
   * Megawatt
   */
  "megawatt": "MW",
  /**
   * Megawattna ura
   */
  "megawatthour": "MWh",
  /**
   * Meter
   */
  "meter": "m",
  /**
   * Meter na uro
   */
  "meterperhour": "m/h",
  /**
   * Meter na minuto
   */
  "meterperminute": "m/min",
  /**
   * Meter na sekundo
   */
  "meterpersecond": "m/s",
  /**
   * Tona
   */
  "metricton": "t",
  /**
   * Tona na uro
   */
  "metrictonperhour": "t/h",
  /**
   * Miliamper
   */
  "miliampere": "mA",
  /**
   * Miligram
   */
  "miligram": "mg",
  /**
   * Milidžul
   */
  "milijoule": "mJ",
  /**
   * Milimeter
   */
  "milimeter": "mm",
  /**
   * Milimeter na sekundo
   */
  "milimeterpersecond": "mm/s",
  /**
   * Milivolt
   */
  "milivolt": "mV",
  /**
   * Milivolt-amper
   */
  "milivoltampere": "mVA",
  /**
   * Milivolt-reaktivni amper
   */
  "milivoltamperereactive": "mVAR",
  /**
   * Miliwatt
   */
  "miliwatt": "mW",
  /**
   * Miliwattna ura
   */
  "miliwatthour": "mWh",
  /**
   * Minuta
   */
  "minute": "min",
  /**
   * Njuton
   */
  "newton": "N",
  /**
   * Brez enote
   */
  "none": "",
  /**
   * Normalni kubični meter
   */
  "normalcubicmeter": "Nm^3",
  /**
   * Delci na milijardo
   */
  "partsperbillion": "ppb",
  /**
   * Delci na milijon
   */
  "partspermillion": "ppm",
  /**
   * Delci na trilijon
   */
  "partspertrillion": "ppt",
  /**
   * Pascal
   */
  "pascal": "Pa",
  /**
   * Odstotek
   */
  "percent": "percent",
  /**
   * Funt na kvadratni palec
   */
  "psi": "psi",
  /**
   * Radian
   */
  "radian": "rad",
  /**
   * Obratov na minuto
   */
  "revolutionsperminute": "rpm",
  /**
   * Sekunda
   */
  "second": "s",
  /**
   * Teradžul
   */
  "terajoule": "TJ",
  /**
   * Volt
   */
  "volt": "V",
  /**
   * Volt-amper
   */
  "voltampere": "VA",
  /**
   * Volt-reaktivni amper
   */
  "voltamperereactive": "VAR",
  /**
   * Watt
   */
  "watt": "W",
  /**
   * Wattna ura
   */
  "watthour": "Wh",
} as const;

export const GeneratedDataSizeMeasurements = {
  /**
   * Bit
   */
  "bit": "bit",
  /**
   * Bajt
   */
  "byte": "B",
  /**
   * Eksabajt
   */
  "exabyte": "EB",
  /**
   * Gigabajt
   */
  "gigabyte": "GB",
  /**
   * Kilobajt
   */
  "kilobyte": "kB",
  /**
   * Megabajt
   */
  "megabyte": "MB",
  /**
   * Petabajt
   */
  "petabyte": "PB",
  /**
   * Terabajt
   */
  "terabyte": "TB",
  /**
   * Jotabajt
   */
  "yottabyte": "YB",
  /**
   * Zetabajt
   */
  "zettabyte": "ZB",
} as const;

export const GeneratedCounterMeasurements = {
  /**
   * Giga
   */
  "giga": "G",
  /**
   * Kilo
   */
  "kilo": "k",
  /**
   * Mega
   */
  "mega": "M",
} as const;

export type GeneratedPhysicalMeasurement = typeof GeneratedPhysicalMeasurements[keyof typeof GeneratedPhysicalMeasurements];
export type GeneratedDataSizeMeasurement = typeof GeneratedDataSizeMeasurements[keyof typeof GeneratedDataSizeMeasurements];
export type GeneratedCounterMeasurement = typeof GeneratedCounterMeasurements[keyof typeof GeneratedCounterMeasurements];
export type GeneratedMeasurementUnit = GeneratedPhysicalMeasurement | GeneratedDataSizeMeasurement | GeneratedCounterMeasurement | (string & {});
